version: '3.9'

services:
  mariadb:
    image: mariadb:10.5
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=froggyfresh
      - MYSQL_DATABASE=froggyfresh